apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-f674
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0025-tenant/tkrw-pr712-0075-0025-app/devfile-sample-f674@sha256:beaea27d82d669241cce9f24987b0ca50b20920f6526d0cfcca2aab32cd1a6da
        name: my-nodejs
        resources: {}
status: {}
